##### introduction Numpy

In [7]:
print("hello")

hello


In [8]:
import numpy as np

a = np.array([20, 30, 40])
b = np.array([60, 70, 80])
print (a)
print (b)
print (a+b)

[20 30 40]
[60 70 80]
[ 80 100 120]


In [9]:
l1 = [20, 30, 40]
l2 = 5
print (l1 * l2)

[20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40]


In [73]:
l1 = [20, 30, 40]
l2 = [50, 60, 70]
print (l1+l2)

[20, 30, 40, 50, 60, 70]


In [13]:
a = np.array([40, 50, 60.0])
a2 = np.array([ [20, 30 , 10],[40, 50, 60] ])
print (a)
print("\n")
print (a2)

[40. 50. 60.]


[[20 30 10]
 [40 50 60]]


In [14]:
l1 = [ [20, 30], [40, 50, 60] ]
print (l1)

[[20, 30], [40, 50, 60]]


##### NymPy - creating arrays, slicing and attributes

In [15]:
import numpy as np

arr = np.array( [10, 20, 30, 40] )
print (arr [2:] )

[30 40]


In [17]:
arr = np.array( [ [10, 20, 30, 40], [50, 60, 70, 80] ])
print (arr[0:2, 0:2])

[[10 20]
 [50 60]]


In [26]:
arr = np.array( [   [10, 20, 30, 40], 
                    [50, 60, 70, 80], 
                    [20, 40, 60, 80] ])

print (arr [2, 1]) # baris, kolom
print (np.shape(arr))
print (np.size(arr))
print (np.ndim(arr))
print (arr.dtype)

40
(3, 4)
12
2
int32


##### inspecting an array

In [28]:
import numpy as np

a = [[30, 40], [40, 30]]
arr = np.array(a)
print (arr)
print (arr.shape)

[[30 40]
 [40 30]]
(2, 2)


In [ ]:
import numpy as np

a = [ [30, 40, 40], [40, 30, 10] ]
arr = np.array(a)
print (arr)
print (arr.shape)           # rows, columns
print (len(arr))            # number of neste values
print (np.size(arr))        # number of elements
print (type (arr))          # datatype of variable
print (arr.dtype)           # datatype of array
print (arr.astype(int))     # conversion of datatype

[[30 40 40]
 [40 30 10]]
(2, 3)
2
6


##### mathematical operations and functions on arrays

In [35]:
arr1 = np.array ( [ [30, 40], [20, 10] ])
arr2 = np.array ([ [30, 20], [10, 20] ])
print (arr1 + arr2)
print (arr1 - arr2)
print (np.add (arr1, arr2))
print (np.subtract (arr1, arr2))

print ("\n")
print (arr1 * arr2)
print (np.multiply (arr1, arr2))

print ("\n")
print (arr1 / arr2)
print (np.divide (arr1, arr2))

[[60 60]
 [30 30]]
[[  0  20]
 [ 10 -10]]
[[60 60]
 [30 30]]
[[  0  20]
 [ 10 -10]]


[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [ ]:
arr1 = np.array ([3, 4, 2, 1])
arr2 = np.array ( [3] )
print (np.power (arr1, arr2)) # setiap elemen arr1 di pangkatkan elemen arr2

[27 64  8  1]


In [38]:
arr1 = np.array ( [9, 16, 4, 1] )
print (np.sqrt (arr1) ) # akar kuadrat dari elemen arr1

[3. 4. 2. 1.]


##### combining and splitting arrays

In [39]:
a = [30, 40, 50]
b = [5, 5, 3]
print (a + b)

[30, 40, 50, 5, 5, 3]


In [40]:
# cocatenate
import numpy as np
arr1 = np.array ( [30, 40, 50] )
arr2 = np.array ([5, 5, 3])
print (np.concatenate ( [arr1, arr2] ))

[30 40 50  5  5  3]


In [44]:
arr1 = np.array ( [ [30, 40], [50, 10] ])
arr2 = np.array ([ [5, 5], [3, 3]])

print (np.concatenate([arr1, arr2]), "\n")
print (np.concatenate([arr1, arr2], axis = 0))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]] 

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [45]:
print (np.hstack ([arr1, arr2])) # horizontal concatenation
print (np.vstack ([arr1, arr2])) # vertical concatenation

[[30 40  5  5]
 [50 10  3  3]]
[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [ ]:
a = np.array ([[20, 40, 30], [40, 10, 20]])
b = np.array_split(a, 3)  # membagi array a menjadi 3 bagian, lalu hasil pembagiannya disimpan ke variabel b.
print (b)

[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int32)]


##### adding and removing elements in the arrays

In [47]:
a = np.array ([ [20, 40], [60, 80] ])
print (np.append(a, [90, 100]))

[ 20  40  60  80  90 100]


In [49]:
print (np.insert (a, 1, [50], axis = 0), "\n") # array, index, value
print (np.insert (a, [1, 2], [50], axis = 0)) 

[[20 40]
 [50 50]
 [60 80]] 

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [50]:
print (np.delete (a, 1))

[20 60 80]


In [51]:
print (a)
print ()
print (np.delete (a, 1, axis = 1))

[[20 40]
 [60 80]]

[[20]
 [60]]


##### Numpy - sort, filter and search

In [52]:
ar = np.array ( [ [7, 8, 4, 12, 9], [2, 8, 5, 1, 3]])
print (np.sort (ar))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [55]:
ar = np.array ( [3, 4, 1, 7, 8])
s = np.where(ar == 4) # search index the elemen
s2 = np.where(ar % 2 == 0)
print (s)
print (s2)

(array([1], dtype=int64),)
(array([1, 4], dtype=int64),)


In [57]:
ar = np.array ( [1, 2, 3, 4, 5] )
ss = np.searchsorted (ar, 5) # search index the elemen
print (ss)

4


In [58]:
ar = np.array ([20, 30, 40, 50] )
fa = [True, False, False, False]

new = ar [fa]
print (new)

[20]


In [59]:
ar = np.array ( [20, 30, 40, 50] )

fa = ar > 35

new = ar [fa]
print (new)

[40 50]


##### aggregating functions in numpy

In [61]:
a = np.array( [20, 40, 60, 70] )

print (np.sum(a))
print (np.min(a))
print (np.max(a))
print (np.size(a))
print (np.mean(a))
print (np.cumsum(a))
print (np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [68]:
a = [100, 150, 199, 200, 250, 130]
b = [10, 50, 30, 40, 30, 10]
price = np.array(a)
quantity = np.array(b)

print (price, "\n", quantity)
print ()
print (np.cumprod([price, quantity], axis = 0))

# can to
print ("\n")
c = np.cumprod( [price, quantity], axis = 0)
print (c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]


31270


##### statistical functions numpy

In [70]:
import statistics as stats
baked_food = [200, 150, 150, 130, 200, 220, 170, 188]

a = np.array (baked_food)

print (np.mean(baked_food))     # sum of all the values/number of values
print (np.median(baked_food))   # central value after sorting
print (stats.mode(baked_food))
print (np.std(baked_food))
print (np.var(baked_food))

176.0
179.0
200
29.017236257093817
842.0


In [71]:
# - 1 represent iversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship
tobacco_consumption = [30, 50, 10, 30, 50, 40]
deaths = [100, 120, 70, 100, 120, 112]

print (np.corrcoef( [tobacco_consumption, deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [72]:
price = [300, 100, 350, 150, 200]
sales = [10, 20, 7, 17, 3]

print (np.corrcoef([price, sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
